### ISSUE TITLE
Functions in docstrings are detected as unused

### ISSUE THREAD

**Issue by ValentinFrancois** [elazarg/uncalled#1]
It is not that uncommon that people write example usage in docstrings, and this can include function definitions.

For example, running `uncalled` with this in the code:

```
def print_args(f):
    """Decorator that print the function arguments before executing it.

    Example:

    ```
    @print_args
    def example_add(x, y):
        return x + y

    if __name__ == "__main__":
        addition(x=1, y=2)
    ```

    => prints "() {'x': 1, 'y': 2}".
    """

    def decorated(*args, **kwargs):
        print(args, kwargs)
        return f(*args, **kwargs)

    return decorated
```

Will output `Unused function example_add`.

---------

People can also use docstrings as 'block comments':
```
"""TODO: uncomment when feature X is merged.

def call_feature_X():
    pass
"""
```
In this case we probably don't want `uncalled` to output `Unused function call_feature_X`.

**Comment by elazarg** [comment]
Thank you!

**Comment by elazarg** [comment]
Published
